# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('icon', models.CharField(blank=True, choices=[(b'fa-linux', b'Linux'), (b'fa-windows ', b'Windows'), (b'fa-apple', b'Apple'), (b'fa-firefox', b'Firefox'), (b'fa-chrome ', b'Chrome'), (b'fa-internet-explorer', b'Internet Explorer'), (b'fa-file', b'Physical File'), (b'fa-file-o', b'Virtual File'), (b'fa-folder', b'Folder'), (b'fa-folder-o', b'Folder White')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('icon', models.CharField(blank=True, choices=[(b'fa-linux', b'Linux'), (b'fa-windows ', b'Windows'), (b'fa-apple', b'Apple'), (b'fa-firefox', b'Firefox'), (b'fa-chrome ', b'Chrome'), (b'fa-internet-explorer', b'Internet Explorer'), (b'fa-file', b'Physical File'), (b'fa-file-o', b'Virtual File'), (b'fa-folder', b'Folder'), (b'fa-folder-o', b'Folder White')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('rank',),
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=512, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('categories', models.ManyToManyField(blank=True, related_name='snippets', to='snippets.Category')),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=132, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=132, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=32, null=True, unique=True)),
                ('icon', models.CharField(blank=True, choices=[(b'fa-linux', b'Linux'), (b'fa-windows ', b'Windows'), (b'fa-apple', b'Apple'), (b'fa-firefox', b'Firefox'), (b'fa-chrome ', b'Chrome'), (b'fa-internet-explorer', b'Internet Explorer'), (b'fa-file', b'Physical File'), (b'fa-file-o', b'Virtual File'), (b'fa-folder', b'Folder'), (b'fa-folder-o', b'Folder White')], max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
