# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20160519_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default=0, max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
