# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_snippet_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='example',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='usage',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
